#!/usr/bin/env python3
"""Reads the Me screens and writes StrandiOS/Nuna/Me/NunaMeSettingsIndex.swift: one entry per setting a screen shows (toggle rows,
section titles, list rows), so search can name the setting and open the screen it lives on. Re-run after adding or renaming settings:
    python3 Tools/gen-me-settings-index.py
"""
import re, subprocess, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "StrandiOS"
VIEWS = {
    "persona": "NunaPersonaView", "zones": "NunaZonesView", "goals": "NunaGoalsView", "devices": ["NunaDevicesView", "NunaDevicesContent", "NunaDeviceDetailView"],
    "anya": "NunaAnyaSettingsView", "appearance": "NunaAppearanceView", "widgets": "NunaWidgetSettingsView",
    "units": "NunaUnitsView", "language": "NunaLanguageView", "features": "NunaFeaturesView",
    "notifications": "NunaNotificationsView", "privacy": "NunaPrivacyView", "automations": "NunaAutomationsView",
    "doubleTap": "NunaDoubleTapView", "presence": "NunaPresenceView", "sessionCues": "NunaSessionCuesView",
    "sedentary": "NunaSedentaryView", "shortcuts": "NunaShortcutsView", "alarm": "NunaSmartAlarmView",
    "data": "NunaDataHubView", "backup": "NunaBackupView", "imports": "NunaImportView", "appleHealth": "NunaAppleHealthView",
    "strava": "NunaStravaView", "hevy": "NunaHevyView", "advanced": "NunaAdvancedView", "experiments": "NunaExperimentsView",
    "testCentre": "NunaTestCentreView", "about": "NunaAboutView",
}
STR = r'"((?:[^"\\]|\\.)*)"'
PATTERNS = [
    ("toggle", re.compile(r'NunaToggleRow\(\s*' + STR + r'(?:\s*,\s*subtitle:\s*' + STR + r')?')),
    ("group", re.compile(r'NunaSettingsGroup\(\s*' + STR)),
    ("row", re.compile(r'NunaListRow\(\s*' + STR + r'(?:\s*,\s*subtitle:\s*' + STR + r')?')),
    ("cap", re.compile(r'nunaTrendsCap\(\s*' + STR)),
    ("step", re.compile(r'NunaStepRow\(\s*label:\s*' + STR)),
]

# Settings the scan cannot see, because the screen builds them from a plain Text label: (route, title, note).
EXTRAS = [
    ("persona", "Date of birth", "Age, used for your heart-rate zones"),
    ("persona", "Sex", "Male, female or non-binary"),
    ("persona", "The day starts", "With main sleep or at 00:00"),
    ("appearance", "Sleep chart", "Classic, Fitbit, Fill, Garmin or Ribbon"),
]

STOP = {"Preview", "Status", "Actions", "Manage", "Connected", "Folder", "Schedule", "Device", "Tools", "Now", "Test", "Examples", "Help", "Credits"}
files = list(SRC.rglob("*.swift"))
text = {f: f.read_text() for f in files}

def body_of(view):
    for f, t in text.items():
        m = re.search(r'^\s*(?:private |fileprivate )?struct ' + view + r'\b[^\n]*\{', t, re.M)
        if m:
            start = m.start()
            rest = t[m.end():]
            end = re.search(r'^(?:private |fileprivate )?(?:struct|enum|final class|class|extension|func)\b', rest, re.M)
            return t[start: m.end() + (end.start() if end else len(rest))], f
    return None, None

def clean(s): return s.replace('\\"', '"')

entries, seen = [], set()
for route, view in VIEWS.items():
    names = view if isinstance(view, list) else [view]
    parts = [body_of(n)[0] for n in names]
    parts = [b for b in parts if b]
    if not parts:
        print("!! no body for", view, file=sys.stderr); continue
    body = "\n".join(parts)
    screen = re.search(r'(?:NunaDetailScreen|NunaHeader)\(\s*' + STR, parts[0])
    for kind, rx in PATTERNS:
        for m in rx.finditer(body):
            title = clean(m.group(1))
            sub = clean(m.group(2)) if m.lastindex and m.lastindex >= 2 and m.group(2) else ""
            if not title or len(title) < 3 or "\\(" in title or title in STOP: continue
            if screen and title == clean(screen.group(1)): continue   # the screen itself is already in the index
            key = (route, title)
            if key in seen: continue
            seen.add(key)
            entries.append((route, title, sub, kind))

for route, title, sub in EXTRAS:
    if (route, title) not in seen:
        seen.add((route, title)); entries.append((route, title, sub, "extra"))

def sw(s): return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
out = ['// Generated by Tools/gen-me-settings-index.py: do not edit by hand.', '#if os(iOS)', '',
       '/// One setting inside a Me screen: its name and note (English keys, translated like the screens themselves) and the screen it opens.',
       'struct NunaMeSetting {', '    let route: NunaMeRoute', '    let title: String', '    let note: String', '}', '',
       'enum NunaMeSettingsIndex {', '    static let all: [NunaMeSetting] = [']
for route, title, sub, kind in entries:
    out.append(f'        .init(route: .{route}, title: {sw(title)}, note: {sw(sub)}),')
out += ['    ]', '}', '#endif', '']
(SRC / "Nuna/Me/NunaMeSettingsIndex.swift").write_text("\n".join(out))
print(len(entries), "settings")
